source "https://rubygems.org"

ruby ">= 3.2"

gem "jekyll", "~> 4.3.2"
gem "webrick", "~> 1.8"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "jekyll-seo-tag"
gem "uri", "~> 0.12.5"
gem "csv"
gem "base64" 